### ISSUE TITLE
RadCalendar dateSelected not firing when inside drawer

### ISSUE THREAD

**Issue by shnhwk** [telerik/nativescript-ui-samples-angular#10]
<GridLayout rows="*, 100" orientation="vertical">
        <RadCalendar [eventSource]="eventSource" 
             (dateSelected)="onDateSelected($event)" row="0">  </RadCalendar>
        <ListView [items]="myItems" rowHeight="44" row="1" >
             <template let-item="item">
                 <StackLayout class="listRow">
                     <Label [text]="item.title"></Label>      
                 </StackLayout>      
             </template>
          </ListView>
    </GridLayout>

    onDateSelected(args: calendarModule.CalendarSelectionEventData) {
        console.log("here");
    }

Wrapped in drawer, nothing when I click on a date, not in the drawer works fine. 
Inline Events works either way.

**Comment by VladimirAmiorkov** [comment]
Hi @shnhwk ,

This was a know issue which has been resolved in the latest **1.3.1** version of [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui)/[nativescript-telerik-ui-pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro). Please give it a try.
