### ISSUE TITLE
RadSideDrawer gap when showOverNavigation

### ISSUE THREAD

**Issue by bastianjoel** [telerik/nativescript-ui-samples-angular#14]
![screenshot_20160707-140547](https://cloud.githubusercontent.com/assets/9317999/16652696/8b7aea6e-444c-11e6-9cc0-ecd4ae6874b3.png)

**Comment by mostafa-raafat** [comment]
can you tell me how you did it ?

**Comment by VladimirAmiorkov** [comment]
hi @bastianjoel ,

We had a similar issue in the older versions of nativescript-telerik-ui which was resolved in the latest versions. Could you try upgrading to ^1.3.1.

I will close the issue, if you continue to experience such issues let us know.
