### ISSUE TITLE
Docker used vwrsion

### ISSUE THREAD

**Issue by joeblew99** [telerik/nativescript-ui-samples-angular#20]
Can a dock file be added please ?

From the host it should be possible to connect to my iOS and android device ? 

Is there any IDE ? It's pretty easy to run using x11 with docker. Ido it with electron for example.

So I am very much hoping you see how this makes it very very easy to get going. Dock build and dock run and just map the volume from you host for the app your building.

There may already be one on github somewhere too.
I just want one that the telerik team support

**Comment by VladimirAmiorkov** [comment]
Hi @joeblew99 ,

Could you elaborate a little more on what you would like to see added/implemented to the nativescript-ui-samples-angualr repo. You are referring to a 'dock file' what do you mean by that. Any additional information that would bring some more light on the desired final result would be very much appreciated.

**Comment by joeblew99** [comment]
sorry about the confusion. 

i mean a docker file.
Basically running the whole thing in a docker file is one approach developers (including me) use.

I can understand if your not interested in doing this though. I can do it myself easily too

**Comment by VladimirAmiorkov** [comment]
@joeblew99 Ok I understand now, well the design of this repo is to showcase the components of the nativescript-telerik-ui/pro while using the Angular 2 environment for education purpose. While merging all of its classes/views into a single file is possible it would make it a lot harder for going through the code and investigating how it works.

As a side question, do you feel like the Angular {N} framework would benefit from such feature where the entire JS project will be "exported" into a single file so it can be ran with Docker?

**Comment by joeblew99** [comment]
@VladimirAmiorkov 
I
 dont see that at DEV time a single JS helps at all.
At runtime, there is a big advantage,, because it makes deploy easier though.


For understanding, what i do is map the folder from my host.
If the code is OS specific, then i just run git in the guest, and push and pull the code from inside the guest.

Does that make sense ?

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#111
