### ISSUE TITLE
RadListView transparent background?

### ISSUE THREAD

**Issue by shnhwk** [telerik/nativescript-ui-samples-angular#22]
The background is always white when I try to do any transparency?  Images and colors work fine.

**Comment by VladimirAmiorkov** [comment]
HI @shnhwk ,

Just to clarify your use case. Could you please share the following information:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

Also could you described in few works the desired behavior in that use case.

**Comment by swapneshran** [comment]
@VladimirAmiorkov 

Same issue also I am facing.  Not able add opacity to Radlist view for iOS. For android it works fine.

The required details are as follows.

. CLI: -2.3.0
. Cross-platform modules :- 2.3.0
. Runtimes : - 2.3.0 (both android and iOS)
. Plugins: -nativescript-telerik-ui:- ^1.4.1 

Thanks in advance.

**Comment by miroslavaivanova** [comment]
I will move this issue to the dedicated GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
