### ISSUE TITLE
Simple Nativescript Angular2-rc5 template with telerik-ui-free support

### ISSUE THREAD

**Issue by Sulman633** [telerik/nativescript-ui-samples-angular#31]
Could someone please if possible make a working or give an existing template that actually works. I have tried the official angular 2 and nativescript template but that still gives issues refer to nsndeck's comment which provides the template but will still cause the same issue. Please if anyone has a working simplified template not like nativescript-ui-samples-angular which shows off features just a simple hello world template.

**Comment by Sulman633** [comment]
nsndeck's comment:
https://github.com/NativeScript/nativescript-angular/issues/423#issuecomment-245468180

**Comment by VladimirAmiorkov** [comment]
Hi @Sulman633 ,

The nativescript-ui-samples-angular repository is designed to showcase the features of the controls in the nativescript-telerik-ui/pro suite when working with Angular 2. Each example for specific control is separated in an Angular 2 component (an .ts, .html and .css files) for example: the SideDrawer's [getting-started](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/sidedrawer/getting-started). This repository is not exactly an template but rather an reference project which can be used when working with the controls from the suite under Angular 2.

On a side note the current [release branch](https://github.com/telerik/nativescript-ui-samples-angular/tree/release)  is compatible with the RC4 version of Angular 2, the [master branch](https://github.com/telerik/nativescript-ui-samples-angular/tree/master)  which is pulled into the release branch with each release of the nativescript-telerik-ui plugin is already been migrated to the RC5 so you can expect full support for RC5 in the nativescript-telerik-ui plugin with our next release later this month.

Angular 2 is in a very dynamic release circle meaning new versions come out almost weekly and we do our best to upgrade or products to its latest version as soon as possible. The current NativeScript Angular template (tns create test-app-name --template angular) still uses the RC4 but we are in the process of upgrading it also.

If you have any other questions or if I have missed something please let us know but reopening the issue.

**Comment by Sulman633** [comment]
Thank you for the quick reply @VladimirAmiorkov . I just have a quick follow up question, the master branch is what worked for me which tells me that I have RC5 but is there a way to go back to Angular RC4? Which is what I was using originally but when I installed the telerik ui for nativescript using this pages instructions:
http://docs.telerik.com/devtools/nativescript-ui/getting-started it updated my nativescript-angular folder to the latest version which changed the structuring of the folder to RC5 structuring which uses modules as you know and caused the error in my previous post.

**Comment by VladimirAmiorkov** [comment]
In order to go back to RC4 currently you can checkout the release branch which has the RC4 structure. The **1.3.1** version of the  [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) plugin was release when the RC4 was the latest Angular 2 version but from all of my tests it works without issues with RC5 also. The mentioned `tns plugin add nativescript-telerik-ui` should not changed any structures of your {N} app, it simply downloads the latest (1.3.1) package of nativescript-telerik-ui to the node_modules folder. Can you explain to me in greater details what structure are you referring to?

**Comment by Sulman633** [comment]
I have tried using the release branch but the problem I mentioned before occurs https://github.com/NativeScript/nativescript-angular/issues/423#issuecomment-245468180 (the first comment where it can't find application.js in nativescript-angular) this happened when I installed nativescript -telerik- ui. I didn't change any dependencies just ran the command above that you mentioned. Now even when I pull your code for release branch it will still give that error.

**Comment by VladimirAmiorkov** [comment]
Are you sure the dependency in the [package.json](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/package.json#L28) for the [nativescript-angular](https://www.npmjs.com/package/nativescript-angular) is for 0.3.0 version. The latest 0.4.0 is upgraded to Angular RC5 in which version the `application.js` is not present.

Also if you are switching from branch to branch its good to manually delete the node_modules, platforms and lib folder to be sure they are not reused incorrectly.

**Comment by Sulman633** [comment]
Currently I don't have access to my computer with the nativescript project so, I will get back to you about that but I usually just rimraf everything and pull your code for release branch, so the package.json shouldn't be different. One more question if I were to use the standard tns create test-app-name --template angular command and then add the telerik-ui for nativescript after that should work correct? Also thank you for your quick responses and help so far :).

**Comment by VladimirAmiorkov** [comment]
Yes the current `tns create test-app-name --template angular` uses the RC4 as do the 1.3.1 version of `nativescript-telerik-ui`. Of course note that this might change when either the  nativescript-telerik-ui version is bumped or the "--template angular" is upgraded, we do try to quickly follow the latest Angular 2 release candidates. The best way to see if both the template project and the pulled from npm nativescript-telerik-ui package are compatible is to simply check their `package.json` files and see what the angular 2 dependencies versions are, if they match all should be ok.

I am glad to help you with this.

**Comment by Sulman633** [comment]
@VladimirAmiorkov I created a new project using the above command you mentioned and it threw the error of not being able to find application.js just like my previous issue here: https://github.com/NativeScript/nativescript-angular/issues/423#

here is a screenshot of package.json of both the template's package.json(left) and nativescript-angular package.json(right).

**Comment by VladimirAmiorkov** [comment]
Hi @Sulman633 ,

I managed to observed the mentioned scenario with a little more descriptive error message pointing to an error in the zone.js package. It looks like as the "tns create app-name --template angular" uses the "Match the most recent major version" for the zone.js and nativescript-angular those most recent major versions introduce changes which are incompatible with that template. Simply remove the `" ^ "` symbol from those packages in the package.json and all should be fine, here is how the dependencies of the template should look like:

```
"dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/platform-server": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "nativescript-angular": "0.3.0",
    "nativescript-telerik-ui": "1.3.1",
    "reflect-metadata": "^0.1.5",
    "rxjs": "5.0.0-beta.6",
    "tns-core-modules": "2.2.1",
    "zone.js": "0.6.12"
  },
```

Note that the current state of Angular 2 is very dynamic and changes on a weekly basis, the best way to keep up-to date with all of the features and changes and the latest news around its release candidates versions is directly in its github repository [here](https://github.com/angular/angular/blob/master/CHANGELOG.md).

**Comment by Sulman633** [comment]
Hi again @VladimirAmiorkov, I just got a chance to try out your solution seems it may have produced progress but I am getting a new error now after removing the " ^ " from zone.js dependency,

java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function

Error: com.tns.NativeScriptException: Failed to find module: "globals", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:241)
    com.tns.Runtime.run(Runtime.java:235)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefrontend/files/app/tns_modules/nativescript-angular/application.js', line: 1, column: 61
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefrontend/files/app/main.js', line: 3, column: 21
Frame: function:'require', file:'', line: 1, column: 266

at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: 
Error calling module function

Error: com.tns.NativeScriptException: Failed to find module: "globals", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:241)
    com.tns.Runtime.run(Runtime.java:235)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefrontend/files/app/tns_modules/nativescript-angular/application.js', line: 1, column: 61
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefrontend/files/app/main.js', line: 3, column: 21
Frame: function:'require', file:'', line: 1, column: 266

at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:241)
at com.tns.Runtime.run(Runtime.java:235)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)

Also I removed ^ from three package.json files one from my app folder, nativescript-angular folder in node module and the package.json in the root folder. Here is what my directory looks like for a better idea (highlighted yellow are where I updated the package.json files):
![packagejsonlocations](https://cloud.githubusercontent.com/assets/11000928/18535454/60a50ed0-7ac2-11e6-8521-ac74b5a01c3f.PNG)

Here are what the package.json files look like in each folder after I updated them:

root folder:
![rootpackage](https://cloud.githubusercontent.com/assets/11000928/18535469/8572e368-7ac2-11e6-8434-a6f20fa70d35.PNG)

app folder:
![apppackage](https://cloud.githubusercontent.com/assets/11000928/18535474/9009a316-7ac2-11e6-84ac-819471174a6a.PNG)

nativescript-angular folder:
![nativescriptangularpackage](https://cloud.githubusercontent.com/assets/11000928/18535483/a04175ec-7ac2-11e6-906e-c04764d91d1b.PNG)

Please let me know what to do next as soon as possible, this problem has plagued me for the last 3 weeks :(

**Comment by Sulman633** [comment]
@VladimirAmiorkov  any update?

**Comment by VladimirAmiorkov** [comment]
@Sulman633 yesterday the official Angular 2.0.0 was released and NativeScript introduced 0 days support fornit with itsNativeScript 2.3.0 and nativescrip-angular 1.0.0. Youcan test thenew template via the --template angular cli commad.

**Comment by Sulman633** [comment]
@VladimirAmiorkov  so that command you told me to use before or this one tns create my-app-name --ng

**Comment by Sulman633** [comment]
Battle Royale

On Fri, Sep 16, 2016 at 2:45 PM, Vladimir Amiorkov <notifications@github.com

**Comment by VladimirAmiorkov** [comment]
@Sulman633 
Yes you could run `tns create your-app-name --template ng` this will create an {N} + Angular project that uses the latest and greatest versions. If you are interested that template is retrieved from [here](https://github.com/NativeScript/template-hello-world-ng).

**Comment by Sulman633** [comment]
@VladimirAmiorkov  after running and creating a new project with the ng template . I am not getting another error and this time its failing to find the 'timers' modulerelative to /app/tns_modules. Seems that any template I use it can't seem to find a module everytime whether it be application.js or this. Could this be an issue with npm or nativescript install?

**Comment by VladimirAmiorkov** [comment]
Are you sure you have all the latest versions of the NativeScript framework. Can you tell us the version that is on your machine by doing `tns --version`. You should be running with 2.3.0 in order to take advantage of the latest 1.0.0 nativescript-angular.

**Comment by Sulman633** [comment]
@VladimirAmiorkov  I figured out that the issue was still from the zone.js folder so I deleted the folder and reinstalled only zone.js. That did the trick and the app works now but it is rc4, I am wondering if you could direct me towards a template with the latest angular 2 release and if telerik ui for nativescript would be compatible with the latest release?

**Comment by Sulman633** [comment]
@VladimirAmiorkov right now the the default angular 2 remplate --ng is rc4 from what I can see in the package.json file.

**Comment by Sulman633** [comment]
@VladimirAmiorkov  any update?

**Comment by VladimirAmiorkov** [comment]
@Sulman633 try using `tns create your-proj-name --template angular` this one always uses the latest version of our "Hello world" {N} + Angular template project.

Yes the latest 1.4.1 version of [nativescript-ui](https://www.npmjs.com/package/nativescript-telerik-ui)/[pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro) is compatible with the official release of Angular 2

**Comment by Sulman633** [comment]
@VladimirAmiorkov it worked!  Thank you very much for your help through out this post, great service! :D
