### ISSUE TITLE
TypeError: Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by sarvagayatri** [telerik/nativescript-ui-samples-angular#32]
JS: EXCEPTION: Error in ./SideDrawerGettingStartedComponent class SideDrawerGett
ingStartedComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: TypeError: Cannot read property 'sideDrawer' of undefine
d
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'sideDrawer' of undefined
JS:     at SideDrawerGettingStartedComponent.ngAfterViewInit (/data/data/org.nat
ivescript.Practise/files/app/drawer/drawer.js:14:43)
JS:     at DebugAppView._View_SideDrawerGettingStartedComponent_Host0.detectChan
gesInternal (SideDrawerGettingStartedComponent.template.js:34:84)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.Pract
ise/files/app/tns_modules/@angular/core/src/linker/view.js:243:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.Practise/file
s/app/tns_modules/@angular/core/src/linker/view.js:348:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nat
ivescript.Practise/files/app/tns_modules/@angular/core/src/linker/view.js:261:19
)
JS:     at DebugAppView._View_DetachedLoader_Host0.detectChangesInternal (Detach
edLoader.template.js:29:8)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.Pract
ise/files/app/tns_modules/@angular/core/src/linker/view.js:243:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.Practise/file
s/app/tns_modules/@angular/core/src/linker/view.js:348:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nat
ivescript.Practise/files/app/tns_modules/@angular/core/src/linker/view.js:261:19
)
JS:     at DebugAppView.AppView.detectChangesInternal (/data/data/org.nativescri
pt.Practise/files/app/tns_modules/@angular/core/src/linker/view.js:253:14)
JS: ERROR CONTEXT:
JS: [object Object]
JS: EXCEPTION: Error in ./SideDrawerGettingStartedComponent class SideDrawerGett
ingStartedComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: TypeError: Cannot read property 'sideDrawer' of undefine
d
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'sideDrawer' of undefined
JS:     at SideDrawerGettingStartedComponent.ngAfterViewInit (/data/data/org.nat
ivescript.Practise/files/app/drawer/drawer.js:14:43)
JS:     at DebugAppView._View_SideDrawerGettingStartedComponent_Host0.detectChan
gesInternal (SideDrawerGettingStartedComponent.template.js:34:84)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.Pract
ise/files/app/tns_modules/@angular/core/src/linker/view.js:243:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.Practise/file
s/app/tns_modules/@angular/core/src/linker/view.js:348:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nat
ivescript.Practise/files/app/tns_modules/@angular/core/src/linker/view.js:261:19
)
JS:     at DebugAppView._View_DetachedLoader_Host0.detectChangesInternal (Detach
edLoader.template.js:29:8)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.Pract
ise/files/app/tns_modules/@angular/core/src/linker/view.js:243:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.Practise/file
s/app/tns_modules/@angular/core/src/linker/view.js:348:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nat
ivescript.Practise/files/app/tns_modules/@angular/core/src/linker/view.js:261:19
)
JS:     at DebugAppView.AppView.detectChangesInternal (/data/data/org.nativescri
pt.Practise/files/app/tns_modules/@angular/core/src/linker/view.js:253:14)
JS: ERROR CONTEXT:
JS: [object Object]

**Comment by VladimirAmiorkov** [comment]
Hi @sarvagayatri ,

Could you give us more details about the issue you are experiencing:

- Which version of nativescript do you have (`tns --version`)
- Have you made any changes to the repository or you are simply running the sdkAngular project

**Comment by sowjanyatammana** [comment]
JS: EXCEPTION: Error in ./SideDrawerGettingStartedComponent class SideDrawerGett
ingStartedComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: TypeError: Cannot read property 'sideDrawer' of undefine
d
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'sideDrawer' of undefined
JS:     at SideDrawerGettingStartedComponent.ngAfterViewInit (/data/data/org.nat
ivescript.groceries/files/app/pages/CookBook/getting-started.component.js:28:43)

JS:     at DebugAppView._View_SideDrawerGettingStartedComponent_Host0.detectChan
gesInternal (SideDrawerGettingStartedComponent.template.js:34:84)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.groce
ries/files/app/tns_modules/@angular/core/src/linker/view.js:243:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.groceries/fil
es/app/tns_modules/@angular/core/src/linker/view.js:348:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nat
ivescript.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:261:1
9)
JS:     at DebugAppView._View_DetachedLoader_Host0.detectChangesInternal (Detach
edLoader.template.js:29:8)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.groce
ries/files/app/tns_modules/@angular/core/src/linker/view.js:243:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.groceries/fil
es/app/tns_modules/@angular/core/src/linker/view.js:348:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nat
ivescript.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:261:1
9)
JS:     at DebugAppView.AppView.detectChangesInternal (/data/data/org.nativescri
pt.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:253:14)
JS: ERROR CONTEXT:
JS: [object Object]
JS: EXCEPTION: Error in ./SideDrawerGettingStartedComponent class SideDrawerGett
ingStartedComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: TypeError: Cannot read property 'sideDrawer' of undefine
d
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'sideDrawer' of undefined
JS:     at SideDrawerGettingStartedComponent.ngAfterViewInit (/data/data/org.nat
ivescript.groceries/files/app/pages/CookBook/getting-started.component.js:28:43)

JS:     at DebugAppView._View_SideDrawerGettingStartedComponent_Host0.detectChan
gesInternal (SideDrawerGettingStartedComponent.template.js:34:84)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.groce
ries/files/app/tns_modules/@angular/core/src/linker/view.js:243:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.groceries/fil
es/app/tns_modules/@angular/core/src/linker/view.js:348:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nat
ivescript.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:261:1
9)
JS:     at DebugAppView._View_DetachedLoader_Host0.detectChangesInternal (Detach
edLoader.template.js:29:8)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.groce
ries/files/app/tns_modules/@angular/core/src/linker/view.js:243:14)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.groceries/fil
es/app/tns_modules/@angular/core/src/linker/view.js:348:44)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nat
ivescript.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:261:1
9)
JS:     at DebugAppView.AppView.detectChangesInternal (/data/data/org.nativescri
pt.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:253:14)
JS: ERROR CONTEXT:
JS: [object Object]

**Comment by sowjanyatammana** [comment]
Having this issue with side drawer component, any one help me.

**Comment by VladimirAmiorkov** [comment]
Hi @sowjanyatammana ,

It looks like you are referning a custom project that is based on the [sample-Groceries](https://github.com/NativeScript/sample-Groceries) merged with the use of the [sidedrawer/getting-started](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/sidedrawer/getting-started) example from this repo. In this case could you share the code of that application. There could be multiple reasons you are getting the mentioned:
> Cannot read property 'sideDrawer' of undefine

Are you by any chance using the "[Showing RadSideDrawer over the navigation bar/action bar](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/getting-started#showing-radsidedrawer-over-the-navigation-baraction-bar)" in an NativeScript + Angular 2 application. If this is the case please note that this feature is not available in projects using Angular 2 and you can follow the progress of this feature request [here](https://github.com/NativeScript/nativescript-angular/issues/394).

**Comment by mostafa-raafat** [comment]
yes  i have this issue since "@angular/core": "2.0.0", release before that side drawer was working fine

**Comment by sarvagayatri** [comment]
https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/sidedrawer/getting-started
This one we did, we just copy pasted the .html,.ts,.css files and loaded plugin like : npm install nativescript-telerik-ui-pro, and ran the app
and getting the above errors

**Comment by mostafa-raafat** [comment]
yes same for me same example

**Comment by sarvagayatri** [comment]
ya even with the above command same error.

**Comment by mostafa-raafat** [comment]
can you open this problem so that any one can help us ?

**Comment by VladimirAmiorkov** [comment]
@sarvagayatri @mostafa-raafat ,

Depending from which version of the Angular RC releases you have upgraded to the 2.0.0 version you may have to change the declarations of your "bootstrap" module. One change that was major between RC5 and 2.0.0 was that now you need to import the XXX_DIRECTIVES rather than XXX_PROVIDERS from the nativescript-ui plugin, like it is shown [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/app.module.ts#L40-L43). You can also take a look at the updated "[Getting Started](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started)" article from our documentation.

Just to clarify are you both experiencing this issue with a clean copy of the [nativescript-ui-samples-angular](https://github.com/telerik/nativescript-ui-samples-angular) project or inside a custom project that uses code snippets from the repo? I am reopening this issue as you requested.

**Comment by mostafa-raafat** [comment]
thank you after add this line it work now 

@NgModule({
    bootstrap: [
        AppComponent
    ],
    declarations: [
        SIDEDRAWER_DIRECTIVES,  ---->       
    ],
    imports: [
        NativeScriptModule,
    ],

**Comment by VladimirAmiorkov** [comment]
Closing this issue.

**Comment by srnaik** [comment]
Adding SIDEDRAWER_DIRECTIVES in the declaration solved the problem..
