### ISSUE TITLE
RadListView with footer crashes when item gets removed

### ISSUE THREAD

**Issue by dbenninger** [telerik/nativescript-ui-samples-angular#35]
I've got an RadListView with a footer, backed by an observable array. I have noticed that it crashes on iOS with the following error message when I remove an item from the observable array:

Sep 28 13:40:09 Davids-MacBook-Pro-2 PBTest[66278]: CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3462:32: EXCEPTION: undefined is not an object (evaluating 'value.view.itemView.bindingContext')
Sep 28 13:40:09 Davids-MacBook-Pro-2 PBTest[66278]: CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3467:36: ORIGINAL STACKTRACE:
Sep 28 13:40:09 Davids-MacBook-Pro-2 PBTest[66278]: CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3468:36: file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:917:61
        forEach@[native code]
        removeUnusedCells@file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:916:36
        onSourceCollectionChanged@file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:889:39
        onSourceCollectionChangedInternal@file:///app/tns_modules/nativescript-telerik-ui/listview/listview-common.js:619:43
        handler@file:///app/tns_modules/ui/core/weak-event-listener.js:30:38
        notify@file:///app/tns_modules/data/observable/observable.js:149:31
        splice@file:///app/tns_modules/data/observable-array/observable-array.js:127:20
...

Looking at the value object in the debugger, I can see that value.view is the footer view and itemView is undefined. 

If I remove the footer, the issue disappears...

I am using nativescript 2.3.0, tns_core_modules 2.3.0 and nativescript-telerik-ui 1.4.1.

I have troubles reproducing this issue with your nativescript-ui-samples-angular code. It seems that adding an *ngIf directive on the RadListView triggers the issue, but removing the *ngIf from my code does not solve it.

**Comment by dbenninger** [comment]
Btw... it works fine on android...

**Comment by VladimirAmiorkov** [comment]
Hi @dbenninger, 

You mentioned that reproducing this issue in the sdkAngular repo is not possible if the ngIf directive is not used, could you share the code of your application which can reproduce this issue? Additionally also please share:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by dbenninger** [comment]
I am afraid I cannot share the code of the real app. I am gonna go back from ObservableArray to a normal Array as a workaround... 

Thanks anyway..

**Comment by imaginationcoder** [comment]
+1

**Comment by imaginationcoder** [comment]
I am getting same error when list refreshed with RadList's 'loadOnDemand' feature and trying to remove the item. 
And is working fine there if we don't use 'loadOnDemand' feature

**Comment by VladimirAmiorkov** [comment]
@imaginationcoder 

Could you share the code of your application which can reproduce this issue? Additionally also please share:

CLI: (run tns --version to fetch it)
Cross-platform modules: (check the 'version' attribute in the
node_modules/tns-core-modules/package.json file in your project)
Runtime(s): (look for the "tns-android" and "tns-ios" properties in the
package.json file of your project)
Plugin(s): (look for the version number in the package.json file of your
project)
