### ISSUE TITLE
Cannot open RadSideDrawer with slide gesture on iOS with Google Maps as main content

### ISSUE THREAD

**Issue by nickcoury** [telerik/nativescript-ui-samples-angular#38]
The issue occurs on iOS. When placing the [Google Maps plugin](https://github.com/dapriett/nativescript-google-maps-sdk) inside of a RadSideDrawer, the slide to open doesn't work because the Google Maps object grabs the touch event.

To reproduce, add a fullscreen Google Maps inside the Side Drawer content area and try to slide to open.  The map will move instead of the drawer opening.  The solution code given below without the `<Label>` will reproduce the problem.

My solution has been to place an invisible label along the same edge of the screen as the drawer, which covers the map and allows the drawer to be grabbed:

```
<StackLayout tkMainContent>
    <AbsoluteLayout width="100%" height="100%">
        <MapView top="0" left="0" width="100%" height="100%" (mapReady)="onMapReady($event)"></MapView>
        <Label top="0" left="0" width="2%" height="100%" text=" "></Label>
    </AbsoluteLayout>
</StackLayout>
```

The issue/solution can be seen in the setup of [this project](https://github.com/nickcoury/nativescript-maps-app/commit/36a19fcbd1c134adf2a3f16d1d988a763f8c85b5).

CLI version: 2.3.0
tns-core-modules: 2.3.0
tns-ios: 2.3.0
nativescript-google-maps-sdk: 1.3.13
nativescript-telerik-ui: 1.4.1
@angular/*: 2.0.0

**Comment by VladimirAmiorkov** [comment]
Hi @nickcoury ,

The mentioned [project](https://github.com/nickcoury/nativescript-maps-app/commit/36a19fcbd1c134adf2a3f16d1d988a763f8c85b5) is not runnable on my end, it looks like there is an issue with the `nativescript-google-maps-sdk` it throws:

> app/pages/map/map.component.ts(4,51): error TS2307: Cannot find module 'nativescript-google-maps-sdk'.

Can you comment on this, maybe some dependencies are missing?

**Comment by VladimirAmiorkov** [comment]
I was able to observe the mentioned behavior and it is caused by the "nativescript-google-maps-sdk" map is handling all of the touch input making any other element to not receive those input. By design the RadSidedDrawer is ontop of all other elements but the google map native element looks to be overriding this behavior which is why the input touch events are not going through to the RadSideDrawer.

The mentioned work around is a good option and we will discus how/if we can improve this behavior in the future versions of the nativescript-telerik-ui/pro plugin. I will tag this issue as "feature improvement" for better tracking.

**Comment by nickcoury** [comment]
Thank you, I will continue the workaround.  For reference, how big is the side area used for opening the side drawer? I want to make the hidden element the same size to keep the functionality the same.

**Comment by skarlatov** [comment]
The side drawer's size equals the drawer content size if the drawerSize property is 0. Otherwise the size equals the value of drawerSize. The layer the handles the touch events, covers the whole screen.

**Comment by miroslavaivanova** [comment]
I will move this issue to the GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
