### ISSUE TITLE
RadListView layouts not identified 

### ISSUE THREAD

**Issue by Sulman633** [telerik/nativescript-ui-samples-angular#41]
As the title states I am getting the following error even though I telerik ui installed when trying to use any layout (http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/item-layouts)  tag for radlistview. I am just using your example radlistview which is working fine with the stacklayout.

![htmllistview](https://cloud.githubusercontent.com/assets/11000928/19332141/5b12574c-90b7-11e6-8204-b1df8cb3bc98.PNG)

ERROR:

com.tns.NativeScriptException: 
Calling js method onCreateViewHolder failed

Error: ListViewLinearLayout is not a valid View instance.
File: "/data/data/org.nativescript.nightlivefront/files/app/tns_modules/ui/core/view-common.js, line: 946, column: 12

StackTrace: 
Frame: function:'View._addView', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/ui/core/view-common.js', line: 946, column: 19
Frame: function:'LayoutBase.insertChild', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 55, column: 14
Frame: function:'ViewUtil.insertChild', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/nativescript-angular/view-util.js', line: 49, column: 24
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/nativescript-angular/renderer.js', line: 137, column: 28
Frame: function:'NativeScriptRenderer.attachViewAfter', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/nativescript-angular/renderer.js', line: 135, column: 23...............

package.json:
![packagejson](https://cloud.githubusercontent.com/assets/11000928/19332155/7ccc9ff0-90b7-11e6-8f01-a0c27822e986.PNG)

directory of telerik ui:
![directory](https://cloud.githubusercontent.com/assets/11000928/19332161/8b8e75ea-90b7-11e6-8eac-5713bd13b55e.PNG)

**Comment by Sulman633** [comment]
@VladimirAmiorkov are the html tags not supported by angular yet? Could this be the cause?

**Comment by VladimirAmiorkov** [comment]
Hi @Sulman633,

It looks like you have misplaced the `ListViewLinearLayout`. It is not supposed to be inside the `tkListItemTemplate` but rather in the RadListView itself like shown in [this](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/listview/item-layouts/listview-item-layouts-grid.component.ios.html#L16) example for a GridLayout or in our docs [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/item-layouts#using-listviewlinearlayout).

Simply move it outside of the `tkListItemTemplate`.
