### ISSUE TITLE
Feature request: `ngIf` support for the `Chart`

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-samples-angular#44]
Ability to `show` and `hide` `Series`, while using `ngIf` directive.
For example:

```
<LineSeries *ngIf="isItemVisible" tkCartesianSeries seriesName="income"  [items]="categoricalSource" categoryProperty="Country" valueProperty="Amount"></LineSeries>
```

**Comment by miroslavaivanova** [comment]
I will move this issue to the GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
