### ISSUE TITLE
RadListView ListViewGridLayout fitting images to screen

### ISSUE THREAD

**Issue by Sulman633** [telerik/nativescript-ui-samples-angular#48]
Hi, this is probably a nooby question but I am still new to nativescript and telerik ui so please bare with me on this. What is the easiest way to fit to screen multiple images that are inside a radlistview which uses ListViewGridLayout(I have proper image sizes for each screen type saved in resources already). Basically i am trying to achieve something like this 
http://docs.telerik.com/devtools/nativescript-ui/controls/NativeScript/ListView/Images/list-view-overview_3.png 

What I have so far right now is this:

![test](https://cloud.githubusercontent.com/assets/11000928/20693638/b6d0fa64-b5ad-11e6-8000-6dc638a3f661.png)

Thanks for the help in advance

**Comment by VladimirAmiorkov** [comment]
Hi @Sulman633 ,

As this question related to best practices and how to it would be best to ask it in our community forums [here](http://www.telerik.com/forums/nativescript-ui/listview) or if you already use the pro version of the plugin submit a support ticket which will be answered no longer than 24 hours after submission, more information regarding the prop plugin can be found [here](http://www.telerik.com/nativescript-ui).
