### ISSUE TITLE
App crashes when navigating back to a listview with a header/footer

### ISSUE THREAD

**Issue by dbenninger** [telerik/nativescript-ui-samples-angular#49]
### Tell us about the problem
If you navigate back to a listview with a custom list view header set. The app crashes with the message: file:///app/tns_modules/ui/core/view-common.js:748:22: JS ERROR TypeError: undefined is not an object (evaluating 'child.onLoaded')
If you remove the header and footer, it works fine.

### Which platform(s) does your issue occur on?
It seems that this only occurs on iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.0
- Cross-platform modules: 2.4.0
- Runtime(s): 2.4.0
- Plugin(s): "nativescript-telerik-ui-pro": "1.5.1"

### Please tell us how to recreate the issue in as much detail as possible.
1. You have to change your header / footer example, to make sure you can select an item and that it navigates to another page with a back button. 
2. Run the example on the ios emulator
3. Go to the header / footer example
4. Select an item, you should navigate to another page
5. Tap the back button
6. The app will crash

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Please have a look at: https://github.com/dbenninger/nativescript-ui-samples-angular/commit/0238f629576420d931812d39c6dcd669ac58076a

**Comment by VladimirAmiorkov** [comment]
Hi @dbenninger ,

Thank you for reporting this to us and for the fully written details, they were very helpful.

I was able to observe the described issue in both the provided {N} + Angular and vanila {N} application and it looks like there is an bug in the current version of the nativescript-telerik-ui/-pro plugin with the RadListView header and footer templates. We will do our best to resolve this issue as soon as possible.

**Comment by VladimirAmiorkov** [comment]
Hi @dbenninger ,

We managed to resolve this issue experienced on iOS and the fix will be available in our next official release. If you want you can use our "next" tagged version in npm which includes all of the daily latest fixes to the plugin before they are officially release:

```
"dependencies": {
    "nativescript-telerik-ui-pro": "next"
  },
```

**Comment by dbenninger** [comment]
Hi @VladimirAmiorkov 
Thanks for your quick fix, it works fine.
