### ISSUE TITLE
RadListView inside RadListView

### ISSUE THREAD

**Issue by jiwonyune** [telerik/nativescript-ui-samples-angular#5]
I have a question about RadListView. Can you put a child RadListView inside a parent RadListView? I would like to test it, but I cannot run NativeScript with Angular because of recent issues with "Cannot find module 'nativescript-telerik-ui/listview/angular/listview-directives'...". Just waiting for the update.

Any insights?

**Comment by ginev** [comment]
Hello @jiwonyune ,

Theoretically you can but why would you? Can you describe your scenario with more details?
