### ISSUE TITLE
I'm Getting 'Failed to find module' error when testing apk

### ISSUE THREAD

**Issue by betosalvador** [telerik/nativescript-ui-samples-angular#50]
## Please, provide the details below:
I'm trying to run a simple example of sidedrawer component, based on this link:
http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/getting-started

But, when I run the app on emulator, I got this error:
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-telerik-ui/sidedrawer/angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
    android.app.ActivityThread.access$1500(ActivityThread.java:135)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
**2.4.1**

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
**2.4.2**

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
**"tns-android": { "version": "2.4.1" }
"tns-ios" (dont have)**

### Please tell us how to recreate the issue in as much detail as possible.
1) Create a new tns project with angular suport
2) Run tns plugin add nativescript-telerik-ui
3) Run tns platform add android
4) Buil and run on emulator (In my case: Genymotion with HTC one android 4.4.4)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

That is my app.module.ts:
```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/platform";
import { AppComponent } from "./app.component";
import { SIDEDRAWER_DIRECTIVES } from 'nativescript-telerik-ui/sidedrawer/angular';

@NgModule({
    declarations: [AppComponent, SIDEDRAWER_DIRECTIVES],
    bootstrap: [AppComponent],
    imports: [NativeScriptModule],
    schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule { }
```

My app.component.html

```
<RadSideDrawer tkExampleTitle tkToggleNavButton>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Social" class="sideLabel"></Label>
            <Label text="Promotions" class="sideLabel"></Label>
            <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Important" class="sideLabel"></Label>
            <Label text="Starred" class="sideLabel"></Label>
            <Label text="Sent Mail" class="sideLabel"></Label>
            <Label text="Drafts" class="sideLabel"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout tkMainContent>
        <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
        <Button text="OPEN DRAWER" (tap)=openDrawer()></Button>
    </StackLayout>
</RadSideDrawer>
```

Thanks in advance

**Comment by betosalvador** [comment]
Hi. Everething is working now.

I followed this tutorial and solve the problem
https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/

thanks!!

**Comment by realtebo** [comment]
@betosalvador Thanks for your solution, I'll try because I've a lot of problems with this component.

Please, could you tell me where did you find info about what to import in `app.module.ts` ? The official documentation is lacking a lot of info about step-to-step start
