### ISSUE TITLE
RadListView - tkListLoadOnDemandTemplate - Label property binding not works

### ISSUE THREAD

**Issue by clarenceh** [telerik/nativescript-ui-samples-angular#52]
## Please, provide the details below:
I am using RadListView with tkListLoadOnDemandTemplate directive for load more action. When I want to use property binding to set the "Load More" label in my component, it fails and only shown blank label on page.

### Which platform(s) does your issue occur on?
iOS/Android/Both
iOS: show blank label
Android: always show "LOAD MORE" in label

### Please provide the following version numbers that your issue occurs with:
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date  │
│ tns-core-modules │ 2.4.3           │ 2.4.3          │ Up to date  │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date  │
│ tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date  │

nativescript-telerik-ui-pro: 1.5.1_184

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Component template:
```
<GridLayout>

    <RadListView id="testList" [items]="contacts | async" loadOnDemandMode="Manual" (loadMoreDataRequested)="onLoadMoreItemsRequested($event)" [listViewLayout]="layout">

        <template tkListItemTemplate let-contact="item">
            <StackLayout (tap)="toDetail()">
                <Label [text]="contact.name"></Label>
            </StackLayout>
        </template>

        <GridLayout *tkListLoadOnDemandTemplate class="loadOnDemandItemGridLayout">
            <Label [text]="loadMoreLabel" horizontalAlignment="center" verticalAlignment="center"></Label>
        </GridLayout>

    </RadListView>

</GridLayout>
```

Component code:
```
export class ItemListComponent implements OnInit {

    itemList: RadListView;

    loadMoreLabel = 'Load More Items';

...
```

iOS:
<img width="374" alt="2016-12-21 10 18 11" src="https://cloud.githubusercontent.com/assets/2868803/21375180/cf970f82-c766-11e6-8eb4-401adfc15692.png">

Android:
<img width="593" alt="2016-12-21 10 19 05" src="https://cloud.githubusercontent.com/assets/2868803/21375202/f232a7fe-c766-11e6-8c6a-5c92ed2d04d9.png">

**Comment by miroslavaivanova** [comment]
I will move this issue to the dedicated GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
