### ISSUE TITLE
tkListViewHeader and ListViewGridLayout with spanCount=2

### ISSUE THREAD

**Issue by jet-lee-m** [telerik/nativescript-ui-samples-angular#53]
Hi,

I have a problem with a **RadListView** that has a **ListViewGridLayout** with a **spanCount=2**.  When I add a **tkListViewHeader**, the header is displayed  wrong on **iOS-Devices**. The width of the header is only on the half screen.  On **Android-Devices** the header is displayed right on the full width of the screen.

Here is my layout code:

` <RadListView [items]='itemData'>`
`<template tkListItemTemplate let-item='item'>`
`...`
`</template>`
`<template tkListViewHeader >...</template>`
`<ListViewGridLayout tkListViewLayout scrollDirection='Vertical' 
                                spanCount="2"></ListViewGridLayout>`
` </RadListView>`

I attached a screenshot of the iOS and Android screens. **The Android screenshot is the desired behavior**.

<img width="787" alt="bildschirmfoto 2016-12-28 um 15 11 35" src="https://cloud.githubusercontent.com/assets/9317606/21524184/7af0082c-cd14-11e6-88ba-ea94632bff0d.png">

Have you any idea?

Thanks

**Comment by Yamilquery** [comment]
Sorry, did you manage to run this application on a physical device with IOS?

**Comment by miroslavaivanova** [comment]
I will move this issue to the GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
