### ISSUE TITLE
Feature: adding `viewModeChange`  event for RadCalendar 

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-samples-angular#54]
To be able to use two way binding for `viewMode` property in NativeScirpt  Angular 2 project, we should have both `viewMode` property and `viewModeChange` event.

[https://angular.io/docs/ts/latest/guide/template-syntax.html#!#two-way](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#two-way)

### Which platform(s) does your issue occur on?
Both

**Comment by miroslavaivanova** [comment]
I will move this issue to the dedicated GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
