### ISSUE TITLE
Make the {N} + Angular application compatible with Angular 2 AoT

### ISSUE THREAD

**Issue by VladimirAmiorkov** [telerik/nativescript-ui-samples-angular#57]
### Tell us about the problem
The current version of the sdkAngular {N} application is not compatible for AoT

### Which platform(s) does your issue occur on?
Both

### Please tell us how to recreate the issue in as much detail as possible.

Following the ["Using Webpack to Bundle Your Code"](http://docs.nativescript.org/tooling/bundling-with-webpack) article leads to errors from ngc after executing:

`$ npm install --save-dev nativescript-dev-webpack`

followed by

`$ npm run start-android-bundle`
or
`$ npm run start-ios-bundle`

**Comment by VladimirAmiorkov** [comment]
Working on this in branch: https://github.com/telerik/nativescript-ui-samples-angular/tree/aot

**Comment by miroslavaivanova** [comment]
I will move this issue to the dedicated GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
