### ISSUE TITLE
Cannot implement SideDrawer component 

### ISSUE THREAD

**Issue by mi6crazyheart** [telerik/nativescript-ui-samples-angular#6]
Everything seems going well except at the time of launching application I'm getting following error - 

![app-lunch-error-](https://cloud.githubusercontent.com/assets/4346688/16545524/2de9c7ca-414b-11e6-9639-d084741d78fe.png)

My folder structure 

![folder-structure](https://cloud.githubusercontent.com/assets/4346688/16545537/61d3cfe0-414b-11e6-9b9c-2d5c74d11a3a.png)

app.component.ts

	import {ListPage} from "./pages/list/list.component";
	import {Component} from "@angular/core";
	import {RouteConfig} from "@angular/router-deprecated";
	import {NS_ROUTER_DIRECTIVES, NS_ROUTER_PROVIDERS} from "nativescript-angular/router";
	import {LoginPage} from "./pages/login/login.component";
	import {SideDrawerEventsComponent} from "./pages/home/home.component";

	@Component({
	  selector: "main",
	  directives: [NS_ROUTER_DIRECTIVES],
	  providers: [NS_ROUTER_PROVIDERS],
	  template: "<page-router-outlet></page-router-outlet>"
	})
	@RouteConfig([
	  //{ path: "/Login", component: LoginPage, name: "Login", useAsDefault: true },
	  { path: "/Home", component: SideDrawerEventsComponent, name: "Home", useAsDefault: true },
	  { path: "/List", component: ListPage, name: "List" }
	])
	export class AppComponent {}

home.component.ts

	import { Component, ElementRef, ViewChild, Inject, OnInit, ChangeDetectorRef } from "@angular/core";
	import { View } from "ui/core/view";
	import { RadSideDrawer } from "nativescript-telerik-ui/sidedrawer";
	import { Page } from "ui/page";
	import { ActionItem } from "ui/action-bar";
	import sideDrawerModule = require('nativescript-telerik-ui/sidedrawer');
	import * as ObservableModule from "data/observable";
	import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui/sidedrawer/angular";

	@Component({
	    moduleId: module.id,
	    //selector: "sidedrawer-events",
	    selector: "my-app",
	    //templateUrl: 'pages/home/home.html',
	    templateUrl: 'home.html',
	    //styleUrls: ['events.component.css']
	})
	export class SideDrawerEventsComponent implements OnInit {
	    private _currentNotification: string;
	    private _sideDrawerTransition: sideDrawerModule.DrawerTransitionBase;

	    constructor( @Inject(Page) private _page: Page, private _changeDetectionRef: ChangeDetectorRef) {
	        this._page.on("loaded", this.onLoaded, this);
	    }

	    @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;
	    private drawer: SideDrawerType;

	    ngAfterViewInit() {
	        this.drawer = this.drawerComponent.sideDrawer;
	        this._changeDetectionRef.detectChanges();
	    }

	    ngOnInit() {
	    }

	    public onLoaded(args) {
	        this._sideDrawerTransition = new sideDrawerModule.PushTransition();
	    }

	    public get sideDrawerTransition(): sideDrawerModule.DrawerTransitionBase {
	        return this._sideDrawerTransition;
	    }

	    public get currentNotification(): string {
	        return this._currentNotification;
	    }

	    public openDrawer() {
	        this.drawer.showDrawer();
	    }

	    public onDrawerOpening() {
	        console.log("Drawer opening");
	        this._currentNotification = "Drawer opening";
	    }

	    public onDrawerOpened() {
	        console.log("Drawer opened");
	        this._currentNotification = "Drawer opened";
	    }

	    public onDrawerClosing() {
	        console.log("Drawer closing");
	        this._currentNotification = "Drawer closing";
	    }

	    public onDrawerClosed() {
	        console.log("Drawer closed");
	        this._currentNotification = "Drawer closed";
	    }
	}

If I'll change the `LoginPage` in my `app.component.ts`  as default route then it's working. But, I update default route to `SideDrawerEventsComponent` it's showing error. Don't know where the bug is ?

**Comment by VladimirAmiorkov** [comment]
Hi @mi6crazyheart ,

After looking through the code snippets I noted that in the app.component there is an `@RouteConfig `declaration that was changed by the angular team in the latest RC3 version. In RC1 the routes where declared via the` @RouteConfig` attribute but this was changed in the RC2 and RC3 versions of angular 2 to a separate RouteConfig variable that should be passed to the bootstapper. 

For an example implementation you can refer this repos navigation via the [app.routes.ts](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/navigation/app.routes.ts) and the [app.ts](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/app.ts) which starts the bootstrapper.
