### ISSUE TITLE
Radlistview is not sliding horizontally

### ISSUE THREAD

**Issue by SumanSingh4** [telerik/nativescript-ui-samples-angular#60]
<GridLayout rows="*"  tkExampleTitle tkToggleNavButton>
    <RadListView #myRadListView [items]="slider" [scrollPosition]="myScrollPosition" row="1">
         <ListViewLinearLayout tkListViewLayout scrollDirection="Horizontal" itemWidth="80">                                   </ListViewLinearLayout>
             <template tkListItemTemplate let-item="item">
                 <GridLayout columns="auto, auto" class="scroll-pane">
                      <Label col="0" [text]="item" height="20" width="20"></Label>
                       <Label col="1" text="*" height="20" width="10"></Label>
                 </GridLayout>
            </template>
    </RadListView>
</GridLayout>

Output is
![screen shot 2017-03-02 at 6 05 45 pm](https://cloud.githubusercontent.com/assets/25900614/23507412/f9dd88d6-ff72-11e6-8c8e-5793ea028cfe.png)

slider is not sliding left or right. Any help

**Comment by miroslavaivanova** [comment]
I will move this issue to the GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
